### ISSUE TITLE
下载代码后不能运行，报错！

### ISSUE THREAD

**Issue by jdsjlzx** [mogoweb/365browser#3]
Caused by: java.lang.ClassCastException: com.android.tools.fd.runtime.BootstrapApplication cannot be cast to org.chromium.base.BaseChromiumApplication
                                                       at org.chromium.base.BaseChromiumApplication.initCommandLine(BaseChromiumApplication.java:116)
                                                       at org.chromium.chrome.browser.ChromeBrowserProvider.onCreate(ChromeBrowserProvider.java:268)
                                                       at android.content.ContentProvider.attachInfo(ContentProvider.java:1730)
                                                       at android.content.ContentProvider.attachInfo(ContentProvider.java:1705)
                                                       at android.app.ActivityThread.installProvider(ActivityThread.java:5034)
                                                       at android.app.ActivityThread.installContentProviders(ActivityThread.java:4629) 
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4569) 
                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:154) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:135) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5298) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:705)

**Comment by mogoweb** [comment]
Please modify your Android Studio settings, turn off Instant Run.
